/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.UserLogin;

import UserInterface.CommunityWorkArea.CommunityJFrame;
import UserInterface.HospitalWorkArea.HospitalJFrame;
import UserInterface.PatientsWorkArea.PatientJFrame;
import UserInterface.DoctorWorkArea.DoctorJFrame;
import UserInterface.SystemWorkArea.SystemJFrame;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import JAVAMainModel.*;

/**
 *
 * @author adity
 */
public class LoginJPanel extends javax.swing.JPanel {

    /**
     * Creates new form LoginJPanel
     */
    public LoginJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Title = new javax.swing.JLabel();
        LoginPage = new javax.swing.JLabel();
        RoleSelect = new javax.swing.JLabel();
        RoleSelectorCB = new javax.swing.JComboBox<>();
        UsernameLbl = new javax.swing.JLabel();
        UsernameTxtField = new javax.swing.JTextField();
        PasswordLbl = new javax.swing.JLabel();
        btnLogin = new javax.swing.JButton();
        txtPassword = new javax.swing.JPasswordField();

        Title.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        Title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Title.setText("HOSPITAL MANAGEMENT SYSTEM");

        LoginPage.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        LoginPage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LoginPage.setText("LOGIN PAGE");

        RoleSelect.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        RoleSelect.setText("Please Select Your Role");

        RoleSelectorCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "System_Admin", "Hospital_Admin", "Community_Admin", "Doctor", "Patient" }));
        RoleSelectorCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RoleSelectorCBActionPerformed(evt);
            }
        });

        UsernameLbl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        UsernameLbl.setText("Username");

        UsernameTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsernameTxtFieldActionPerformed(evt);
            }
        });

        PasswordLbl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        PasswordLbl.setText("Password");

        btnLogin.setText("LOGIN");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Title, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 737, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(LoginPage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(UsernameLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RoleSelect, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PasswordLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(RoleSelectorCB, 0, 239, Short.MAX_VALUE)
                            .addComponent(UsernameTxtField)
                            .addComponent(txtPassword))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(329, 329, 329))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Title, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LoginPage)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RoleSelect, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RoleSelectorCB, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UsernameLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UsernameTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(PasswordLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtPassword)
                        .addGap(3, 3, 3)))
                .addGap(18, 18, 18)
                .addComponent(btnLogin)
                .addGap(0, 273, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void RoleSelectorCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RoleSelectorCBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RoleSelectorCBActionPerformed

    private void UsernameTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsernameTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UsernameTxtFieldActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:

        UserRoles userRole = UserRoles.valueOf(RoleSelectorCB.getSelectedItem().toString());
        String username = UsernameTxtField.getText();
        String password = new String(txtPassword.getPassword());
        Boolean loginStatus = false;
        
        try{
            
            if((username != null && !username.trim().isEmpty()) && (password != null && !password.trim().isEmpty())){

                if(userRole.equals(UserRoles.System_Admin)){        
                    if(username.equals("s") && password.equals("s")){              
                        reset();
                        loginStatus = true;
                        JFrame mainFrame = (JFrame) SwingUtilities.getRoot(this);
                        mainFrame.dispose();
                        SystemJFrame systemFrame = new SystemJFrame(username);             
                        systemFrame.main(null);
                    }
                    else{
                        loginStatus = false;
                    } 
                }

                if(userRole.equals(UserRoles.Community_Admin)){        
                    if(username.equals("c") && password.equals("c")){              
                        reset();
                        loginStatus = true;
                        JFrame mainFrame = (JFrame) SwingUtilities.getRoot(this);
                        mainFrame.dispose();
                        CommunityJFrame communityFrame = new CommunityJFrame(username);             
                        communityFrame.main(null);
                    }
                    else{
                        loginStatus = false;
                    } 
                }

                if(userRole.equals(UserRoles.Hospital_Admin)){        
                    if(username.equals("h") && password.equals("h")){              
                        reset();
                        loginStatus = true;
                        JFrame mainFrame = (JFrame) SwingUtilities.getRoot(this);
                        mainFrame.dispose();
                        HospitalJFrame hospitalFrame = new HospitalJFrame(username);             
                        hospitalFrame.main(null);
                    }
                    else{
                        loginStatus = false;
                    } 
                }

                if(userRole.equals(UserRoles.Doctor)){
                    if(! username.equals("") && password.equals("")){
                        if(username.equals("d") && password.equals("d")){              
                            reset();
                            loginStatus = true;
                            JFrame mainFrame = (JFrame) SwingUtilities.getRoot(this);
                            mainFrame.dispose();
                            DoctorJFrame doctorFrame = new DoctorJFrame(username);             
                            doctorFrame.main(null);
                        }
                        else{
                             loginStatus = false;
                        }
                    }
                }

                if(userRole.equals(UserRoles.Patient)){
                    if(! username.equals("") && password.equals("")){
                        if(username.equals("p") && password.equals("p")){              
                            reset();
                            loginStatus = true;
                            JFrame mainFrame = (JFrame) SwingUtilities.getRoot(this);
                            mainFrame.dispose();
                            PatientJFrame patientFrame = new PatientJFrame(username);             
                            patientFrame.main(null);
                        }
                        else{
                             loginStatus = false;
                        }
                    }
                }
            }

            if(loginStatus == false){
                JOptionPane.showMessageDialog(this, "Please enter correct credentials!");
                reset();
            }

            
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "Please try Again");
            reset();
        }
    }//GEN-LAST:event_btnLoginActionPerformed


    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LoginPage;
    private javax.swing.JLabel PasswordLbl;
    private javax.swing.JLabel RoleSelect;
    private javax.swing.JComboBox<String> RoleSelectorCB;
    private javax.swing.JLabel Title;
    private javax.swing.JLabel UsernameLbl;
    private javax.swing.JTextField UsernameTxtField;
    private javax.swing.JButton btnLogin;
    private javax.swing.JPasswordField txtPassword;
    // End of variables declaration//GEN-END:variables

    private void reset() {
        UsernameTxtField.setText(null);
        txtPassword.setText(null);
    }
}
