/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.SystemWorkArea.Doctor;

import model.DoctorDirectory;
import model.PersonDirectory;
/**
 *
 * @author Aditya
 */
public class SystemDoctorWorkPanel extends javax.swing.JPanel {

    PersonDirectory personDirectory;
    DoctorDirectory doctorDirectory;
    /**
     * Creates new form SystemDoctorWorkPanel
     */
    public SystemDoctorWorkPanel(PersonDirectory personDirectory,DoctorDirectory doctorDirectory) {
        initComponents();
        this.personDirectory = personDirectory;
        this.doctorDirectory = doctorDirectory;
              
        SystemViewDoctor systemViewDoctor = new SystemViewDoctor(personDirectory,doctorDirectory);
        splitPane.setRightComponent(systemViewDoctor );
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        splitPane = new javax.swing.JSplitPane();
        patientWorkArea = new javax.swing.JPanel();
        controlPanel = new javax.swing.JPanel();
        btnViewDoctor = new javax.swing.JButton();
        btnCreateDoctor = new javax.swing.JButton();
        btnUpdateDoctor = new javax.swing.JButton();

        splitPane.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        patientWorkArea.setBackground(new java.awt.Color(153, 255, 255));

        javax.swing.GroupLayout patientWorkAreaLayout = new javax.swing.GroupLayout(patientWorkArea);
        patientWorkArea.setLayout(patientWorkAreaLayout);
        patientWorkAreaLayout.setHorizontalGroup(
            patientWorkAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 927, Short.MAX_VALUE)
        );
        patientWorkAreaLayout.setVerticalGroup(
            patientWorkAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 353, Short.MAX_VALUE)
        );

        splitPane.setRightComponent(patientWorkArea);

        controlPanel.setBackground(new java.awt.Color(153, 255, 255));
        controlPanel.setMaximumSize(new java.awt.Dimension(150, 100));
        controlPanel.setPreferredSize(new java.awt.Dimension(150, 100));
        controlPanel.setVerifyInputWhenFocusTarget(false);

        btnViewDoctor.setBackground(new java.awt.Color(0, 255, 255));
        btnViewDoctor.setText("View Doctors");
        btnViewDoctor.setMaximumSize(new java.awt.Dimension(10, 5));
        btnViewDoctor.setMinimumSize(new java.awt.Dimension(10, 5));
        btnViewDoctor.setPreferredSize(new java.awt.Dimension(10, 5));
        btnViewDoctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewDoctorActionPerformed(evt);
            }
        });

        btnCreateDoctor.setBackground(new java.awt.Color(0, 255, 255));
        btnCreateDoctor.setText("Create Doctor");
        btnCreateDoctor.setMaximumSize(new java.awt.Dimension(10, 5));
        btnCreateDoctor.setMinimumSize(new java.awt.Dimension(10, 5));
        btnCreateDoctor.setPreferredSize(new java.awt.Dimension(10, 5));
        btnCreateDoctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateDoctorActionPerformed(evt);
            }
        });

        btnUpdateDoctor.setBackground(new java.awt.Color(0, 255, 255));
        btnUpdateDoctor.setText("Update Doctor");
        btnUpdateDoctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateDoctorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout controlPanelLayout = new javax.swing.GroupLayout(controlPanel);
        controlPanel.setLayout(controlPanelLayout);
        controlPanelLayout.setHorizontalGroup(
            controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controlPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnViewDoctor, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCreateDoctor, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnUpdateDoctor, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(547, Short.MAX_VALUE))
        );
        controlPanelLayout.setVerticalGroup(
            controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controlPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnViewDoctor, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCreateDoctor, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdateDoctor, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        splitPane.setLeftComponent(controlPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(splitPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(splitPane, javax.swing.GroupLayout.DEFAULT_SIZE, 409, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnViewDoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewDoctorActionPerformed
        // TODO add your handling code here:
        SystemViewDoctor systemViewDoctor = new SystemViewDoctor(personDirectory, doctorDirectory);
        splitPane.setRightComponent(systemViewDoctor );
    }//GEN-LAST:event_btnViewDoctorActionPerformed

    private void btnCreateDoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateDoctorActionPerformed
        // TODO add your handling code here:
        SystemCreateDoctor systemCreateDoctor = new SystemCreateDoctor(personDirectory, doctorDirectory);
        splitPane.setRightComponent(systemCreateDoctor);
    }//GEN-LAST:event_btnCreateDoctorActionPerformed

    private void btnUpdateDoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateDoctorActionPerformed
        // TODO add your handling code here:
        SystemUpdateDoctor systemUpdateDoctor = new SystemUpdateDoctor(personDirectory,doctorDirectory);
        splitPane.setRightComponent(systemUpdateDoctor);
    }//GEN-LAST:event_btnUpdateDoctorActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreateDoctor;
    private javax.swing.JButton btnUpdateDoctor;
    private javax.swing.JButton btnViewDoctor;
    private javax.swing.JPanel controlPanel;
    private javax.swing.JPanel patientWorkArea;
    private javax.swing.JSplitPane splitPane;
    // End of variables declaration//GEN-END:variables
}
